# Generated by Django 4.1.4 on 2023-01-13 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('locality', models.CharField(max_length=200, null=True)),
                ('city', models.DateTimeField(auto_now_add=True, null=True)),
                ('mobile', models.IntegerField(default=0)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Rajasthan', 'Rajasthan'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Nagaland', 'Nagaland'), ('Sikkim', 'Sikkim'), ('Manipur', 'Manipur'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Maharashtra', 'Maharashtra'), ('Tamil Nadu', 'Tamil Nadu'), ('Odisha', 'Odisha'), ('Goa', 'Goa'), ('Karnataka', 'Karnataka'), ('Chhattisgarh', 'Chhattisgarh'), ('Gujarat', 'Gujarat'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura'), ('West Bengal', 'West Bengal'), ('Jharkhand', 'Jharkhand'), ('Meghalaya', 'Meghalaya'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
