# Generated by Django 4.1.4 on 2023-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Rajasthan', 'Rajasthan'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Nagaland', 'Nagaland'), ('Sikkim', 'Sikkim'), ('Manipur', 'Manipur'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Maharashtra', 'Maharashtra'), ('Tamil Nadu', 'Tamil Nadu'), ('Odisha', 'Odisha'), ('Goa', 'Goa'), ('Karnataka', 'Karnataka'), ('Chhattisgarh', 'Chhattisgarh'), ('Gujarat', 'Gujarat'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura'), ('West Bengal', 'West Bengal'), ('Jharkhand', 'Jharkhand'), ('Meghalaya', 'Meghalaya'), ('Jammu & Kashmir', 'Jammu & Kashmir')], max_length=100, null=True),
        ),
    ]
